### PR TITLE
Use sysctl --system instead of the broken manual loading

### PR DESCRIPTION
**Pull request by faulesocke**
See also https://github.com/void-linux/void-packages/pull/12439 for the reasoning.

### CODE REVIEW

**Comment by Duncaen** [comment]
There was a reason we are not using system, but this issue was in the old repository.
https://github.com/void-linux/void-runit/pull/1

**Comment by faulesocke** [comment]
Seems like the issue here is busybox/procps-ng compatibility?

Well at least we have to do *something* to re-enable kexec for those who want it. Maybe remove it completely from `10-void.conf` and instead whack a manual `sysctl` call inside a separate script under `/etc/runit/core-services/` so that we can enable/disable that using `/etc/rc.conf`?

**Comment by CameronNemo** [comment]
I would rather just fix the sysctl file handling to be more like sysctl --system, so that we can override 10-void.conf if necessary. There are a few more non-reversible actions in there, from what I remember.

**Comment by CameronNemo** [comment]
This can be closed as it has been completely superseded by the merged #31.

**Pull request closed without merging**
