### PR TITLE
core-services/03-filesystems.sh: don't fsck mounted filesystems

### PR DESCRIPTION
**Pull request by classabbyamp**
see also: void-linux/void-packages#50124

### CODE REVIEW

**Comment by ahesford** [comment]
I'd rather be more explicit about solving the issue and avoid tying behavior to specific knowledge about the kernel. How about this flow instead:

1. Explicitly run `fsck -T /`, maybe with a few sanity checks to make sure it is a fsck-able filesystem. (For example, maybe require it be listed in /etc/fstab.)
2. If the exit code is 0 or 8, assume everything is fine and continue. Otherwise, drop to an emergency shell.
3. Allow the current `fsck -A` behavior, except with `-R` to skip the root.

This will catch most common cases, but may still cause problems for people that do things like separate `/usr`. Those users can decide between alternative options, like setting a zero pass number in `/etc/fstab` to skip the affected filesystems altogether, or overriding the kernel restriction.

**Comment by ahesford** [comment]
If we want to catch other cases, we could also step through `mtab` and fsck everything there that starts with `/dev`, consume any error 8's, then run `fsck -M` to skip everything else that we haven't checked.

**Comment by classabbyamp** [comment]
tested the latest version on 6.8.9, works

**Comment by ahesford** [comment]
1. When I run `fsck -T /` on my running system, it runs e2fsck and complains loudly that it can't find a superblock on my (ZFS) root. Does that warning not appear in your testing?
2. I just re-read the man page for fsck and now wonder if any of this is necessary. If the docs are correct, the status for a multi-filesystem check is the bitwise-or of the status for each check. Because we want to trigger an emergency shell if *any* of the checked filesystems return a status besides `0x0` or `0x8`, it seems sufficient to keep our existing `fsck -A` and just accept a return code of 8 as a successful result.

**Pull request merged**
