### PR TITLE
urandom and sysctl fixes

### PR DESCRIPTION
**Pull request by CameronNemo**
Supersedes: #1 #12 #14 #20 #21
Related to: https://github.com/void-linux/void-packages/pull/5002 https://github.com/void-linux/void-packages/pull/12439

### CODE REVIEW

**Comment by Duncaen** [comment]
Not a fan of restructuring this tbh.

**Comment by CameronNemo** [comment]
that is fine. feel free to take the patches without attribution.

**Comment by xtraeme** [comment]
@cameronnemo don't take it offensively. Everyone has their own opinion, we
are humans after all. I was aware of the downsides when we choose runit.
This is one of them. We just need to a consensus in how to proceed with
one-shot services. I'd like to see this asap.

Cheers

**Comment by CameronNemo** [comment]
This has no oneshot related commits. The two user impacting commits are fairly barebones but also important. Long standing frustration from sysctl handling. I tried to address the issues in November but never got anywhere on this side. base files was closed out only recently.

**Comment by xtraeme** [comment]
So we'll have to do something with this asap.

**Comment by CameronNemo** [comment]
@xtraeme I left a patch in #1 ... just need it applied to the right file, and distributed. Until then they need to edit the /usr files directly and use preserve= with xbps.

**Comment by CameronNemo** [comment]
Superseded by #31 and #88

**Pull request closed without merging**
