### PR TITLE
halt: add support for wtmp

### LINKED ISSUE #27: Write BOOT_TIME utmp record
I recently stumbled upon the fact that runit does not write a BOOT_TIME time record into utmp after booting the system. Libvirt relies on such an entry being present to determine the host boot time since version 5.7.0 and fails to start VMs otherwise.

Since runit does not provide the functionality itself, perhaps this could be implemented as part of the boot scripts? Instead of just creating the file as an empty file, one could execute a script or binary to create an initial record after booting the system.

### PR DESCRIPTION
**Pull request by leahneukirchen**
This implements -w and -d.

Also add -B to create boot-time wtmp entries.

Closes #27.

### CODE REVIEW

**Comment by leahneukirchen** [comment]
Please test, I looked at sysvinit but I'm not sure I got all fields right.

**Comment by leahneukirchen** [comment]
Note that this does not use any locking, so ensure nothing else writes during that time (should do an atomic append tho).

**Comment by Hoshpak** [comment]
This seems to work fine for wtmp. However for libvirt it would also be required in `/run/utmp` since it uses `getutxid` to get the record. I couldn't grasp the whole sysvinit code regarding in the meantime however it seems to me that sysvinit also writes to both files. I quickly looked at my Debian server using sysvinit and it also had boot entries in both utmp and wtmp.

**Comment by leahneukirchen** [comment]
Ok, I'll add that.

**Comment by Hoshpak** [comment]
Tested it again, the records look correct to me and it also makes libvirtd work properly again.

**Pull request merged**
