### PR TITLE
Update 08-sysctl.sh

### PR DESCRIPTION
**Pull request by josephg5**
So admin settings are correctly applied to override default settings.

### CODE REVIEW

**Comment by CameronNemo** [comment]
sysctl behavior should use lexicographical priority foremost, and allow for file masking. The adjustment here is a partial solution. The `modules-load` script in this repository has the proper logic, it just needs to be adapted to the sysctl directories and command.

**Comment by josephg5** [comment]
yes sysctl behaviour should use lexicographical priority and my change is not changing that at all. i'm asking for a change in the order of the directories called. as it is, any admin scripts in /etc/ sysctl.d/ are overwritten by /lib/sysctl.d which is the reverse of what is expected. i'm not asking to change the modules-load script or the logic in there, which is perfectly fine.

**Comment by CameronNemo** [comment]
I'm not asking for a change to the modules-load behavior either. On the contrary, I would like to align the sysctl behavior with that of modules-load. In such a situation, an admin would be able to overwrite void.conf (or 00-defaults.conf) using a higher lexicographic priority. For now you must use a file with with a w, x, y, or z at the beginning of the name, but I have a patch so you can use a priority like 90-.

Anyway, if you have admin settings that you would not like overwritten, put them in /etc/sysctl.conf or /etc/sysctl.d/zadmin. conf

**Comment by CameronNemo** [comment]
This can be closed as it has been completely superseded by the merged #31.

**Pull request closed without merging**
