### PR TITLE
Split run-level 3 script into separate files.

### PR DESCRIPTION
**Pull request by basploeger**
This is an attempt to implement the shutdown part of #23. This also supersedes both #56 and #29 (shutdown part only). 

From #56 and [my own use case](http://www.apcupsd.org/manual/manual.html#shutdown-sequence) (for which I need to add shutdown logic  just before halt), it is clear that users need to be able to control at which point in the shutdown sequence their custom logic gets executed. A single hook point like in #29 is not flexible enough.

I think the easiest solution is to source scripts from a specific directory in lexicographic order, which is exactly how `core-services` are already started in run-level 1. I called the directory `stop-services` for analogy, but am open to suggestions [_edit:_ we eventually agreed on `shutdown.d`]. I left gaps in the scripts' priority numbers as needed to allow for custom logic to be injected at those places.

### CODE REVIEW

**Comment by ahesford** [comment]
I like this idea and have no suggestion for a better directory name.

**Comment by Vaelatern** [comment]
Will quibble on the name:
Maybe
`/etc/runit/shutdown.d`?

**Comment by dataCobra** [comment]
This is a better approach. Thanks @ahesford for mentioning it.

I'll close my PR #95. What do we need to do for getting this merged?

**Comment by classabbyamp** [comment]
I like this, and agree with vaelatern's name suggestion

**Comment by ahesford** [comment]
@void-linux/pkg-committers

**Comment by Vaelatern** [comment]
I continue to hold my position that I like the proposal, and that I still think `/etc/runit/shutdown.d` is reasonable.

**Comment by abenson** [comment]
> This also supersedes [...] #29 (shutdown part only).

I agree.  

> I called the directory stop-services for analogy, but am open to suggestions.

I think the name you pick is fine, but so is Vaelatern's.  Both seem reasonable.

**Comment by basploeger** [comment]
Thanks for all the feedback! By popular request I have renamed the stop-services/ directory to shutdown.d/

Could I ask for this to be reviewed now?

**Review by Vaelatern — APPROVED** [review]
Not changing any functionality, adding the ability to tune more functionality later, I like it.

**Review by classabbyamp — APPROVED** [review]

**Review by ahesford — APPROVED** [review]

**Comment by basploeger** [comment]
Thanks for the approvals. Whom do I ask to merge this PR?

**Comment by ahesford** [comment]
Let's let it sit awhile longer in case any late arrivals raise objections, but one of us will merge after a bit.

**Review by Piraty — APPROVED** [review]

**Comment by basploeger** [comment]
Can this be merged now or do you want to wait longer?

**Pull request merged**
